#from app import app
from database import db, Player, Match
from datetime import datetime

def seed_players():
    if True:  # context already active when called from app.py
        Player.query.delete()
        db.session.commit()

        players = [
            Player(name="Noor Ahmad", ipl_team="Chennai Super Kings", role = "bowler", credits=8.5),
            Player(name="Ruturaj Gaikwad", ipl_team="Chennai Super Kings", role = "batsman", credits=10),
            Player(name="Sanju Samson", ipl_team="Chennai Super Kings", role = "keeper", credits=9.5),
            Player(name="Shivam Dube", ipl_team="Chennai Super Kings", role = "allrounder", credits=9),
            Player(name="Dewald Brevis", ipl_team="Chennai Super Kings", role = "batsman", credits=9),
            Player(name="Matt Henry", ipl_team="Chennai Super Kings", role = "bowler", credits=9),
            Player(name="Khaleel Ahmed", ipl_team="Chennai Super Kings", role = "bowler", credits=8.5),
            Player(name="MS Dhoni", ipl_team="Chennai Super Kings", role = "keeper", credits=8.5),
            Player(name="Ayush Mhatre", ipl_team="Chennai Super Kings", role = "batsman", credits=8.5),
            Player(name="Anshul Kamboj", ipl_team="Chennai Super Kings", role = "allrounder", credits=8),
            Player(name="Shreyas Gopal", ipl_team="Chennai Super Kings", role = "allrounder", credits=8.5),
            Player(name="Jamie Overton", ipl_team="Chennai Super Kings", role = "allrounder", credits=8.5),
            Player(name="Matthew Short", ipl_team="Chennai Super Kings", role = "allrounder", credits=8.5),
            Player(name="Sarfaraz Khan", ipl_team="Chennai Super Kings", role = "batsman", credits=8.5),
            Player(name="Akeal Hosein", ipl_team="Chennai Super Kings", role = "bowler", credits=8),
            Player(name="Zak Foulkes", ipl_team="Chennai Super Kings", role = "allrounder", credits=8),
            Player(name="Rahul Chahar", ipl_team="Chennai Super Kings", role = "bowler", credits=8.5),
            Player(name="Gurjapneet Singh", ipl_team="Chennai Super Kings", role = "bowler", credits=8),
            Player(name="Mukesh Choudhary", ipl_team="Chennai Super Kings", role = "bowler", credits=8),
            Player(name="Urvil Patel", ipl_team="Chennai Super Kings", role = "keeper", credits=7.5),
            Player(name="Ramakrishna Ghosh", ipl_team="Chennai Super Kings", role = "bowler", credits=7.5),
            Player(name="Aman Khan", ipl_team="Chennai Super Kings", role = "allrounder", credits=7),
            Player(name="Kartik Sharma", ipl_team="Chennai Super Kings", role = "keeper", credits=7),
            Player(name="Prashant Veer", ipl_team="Chennai Super Kings", role = "allrounder", credits=7),
            Player(name="Spencer Johnson", ipl_team="Chennai Super Kings", role = "bowler", credits=8),
            Player(name="KL Rahul", ipl_team="Delhi Capitals", role = "keeper", credits=10),
            Player(name="Axar Patel", ipl_team="Delhi Capitals", role = "allrounder", credits=9.5),
            Player(name="Mitchell Starc", ipl_team="Delhi Capitals", role = "bowler", credits=8.5),
            Player(name="Kuldeep Yadav", ipl_team="Delhi Capitals", role = "bowler", credits=9),
            Player(name="Tristan Stubbs", ipl_team="Delhi Capitals", role = "batsman", credits=9),
            Player(name="David Miller", ipl_team="Delhi Capitals", role = "batsman", credits=9),
            Player(name="Pathum Nissanka", ipl_team="Delhi Capitals", role = "batsman", credits=8.5),
            Player(name="Vipraj Nigam", ipl_team="Delhi Capitals", role = "bowler", credits=8),
            Player(name="Abishek Porel", ipl_team="Delhi Capitals", role = "keeper", credits=8.5),
            Player(name="Mukesh Kumar", ipl_team="Delhi Capitals", role = "bowler", credits=8.5),
            Player(name="Nitish Rana", ipl_team="Delhi Capitals", role = "batsman", credits=8.5),
            Player(name="Ashutosh Sharma", ipl_team="Delhi Capitals", role = "batsman", credits=8),
            Player(name="Karun Nair", ipl_team="Delhi Capitals", role = "batsman", credits=8),
            Player(name="Kyle Jamieson", ipl_team="Delhi Capitals", role = "allrounder", credits=8.5),
            Player(name="T Natarajan", ipl_team="Delhi Capitals", role = "bowler", credits=8.5),
            Player(name="Lungi Ngidi", ipl_team="Delhi Capitals", role = "bowler", credits=8.5),
            Player(name="Prithvi Shaw", ipl_team="Delhi Capitals", role = "batsman", credits=8),
            Player(name="Sameer Rizvi", ipl_team="Delhi Capitals", role = "batsman", credits=8),
            Player(name="Madhav Tiwari", ipl_team="Delhi Capitals", role = "allrounder", credits=8),
            Player(name="Dushmantha Chameera", ipl_team="Delhi Capitals", role = "bowler", credits=8.5),
            Player(name="Ajay Mandal", ipl_team="Delhi Capitals", role = "allrounder", credits=7.5),
            Player(name="Tripurana Vijay", ipl_team="Delhi Capitals", role = "bowler", credits=7),
            Player(name="Auqib Nabi", ipl_team="Delhi Capitals", role = "bowler", credits=7),
            Player(name="Sahil Parakh", ipl_team="Delhi Capitals", role = "batsman", credits=7),
            Player(name="Jos Buttler", ipl_team="Gujarat Titans", role = "keeper", credits=9.5),
            Player(name="Sai Sudharsan", ipl_team="Gujarat Titans", role = "batsman", credits=9.5),
            Player(name="Shubman Gill", ipl_team="Gujarat Titans", role = "batsman", credits=10.5),
            Player(name="Prasidh Krishna", ipl_team="Gujarat Titans", role = "bowler", credits=8.5),
            Player(name="Mohammed Siraj", ipl_team="Gujarat Titans", role = "bowler", credits=9),
            Player(name="Washington Sundar", ipl_team="Gujarat Titans", role = "allrounder", credits=9),
            Player(name="Glenn Phillips", ipl_team="Gujarat Titans", role = "allrounder", credits=9),
            Player(name="Rashid Khan", ipl_team="Gujarat Titans", role = "allrounder", credits=9),
            Player(name="Kagiso Rabada", ipl_team="Gujarat Titans", role = "bowler", credits=8.5),
            Player(name="Sai Kishore", ipl_team="Gujarat Titans", role = "bowler", credits=8),
            Player(name="Arshad Khan", ipl_team="Gujarat Titans", role = "bowler", credits=8),
            Player(name="Jason Holder", ipl_team="Gujarat Titans", role = "allrounder", credits=8.5),
            Player(name="Tom Banton", ipl_team="Gujarat Titans", role = "batsman", credits=8.5),
            Player(name="Luke Wood", ipl_team="Gujarat Titans", role = "bowler", credits=8),
            Player(name="Ishant Sharma", ipl_team="Gujarat Titans", role = "bowler", credits=8.5),
            Player(name="Rahul Tewatia", ipl_team="Gujarat Titans", role = "batsman", credits=8.5),
            Player(name="Nishant Sindhu", ipl_team="Gujarat Titans", role = "allrounder", credits=8),
            Player(name="Anuj Rawat", ipl_team="Gujarat Titans", role = "keeper", credits=8),
            Player(name="Manav Suthar", ipl_team="Gujarat Titans", role = "bowler", credits=8),
            Player(name="M Shahrukh Khan", ipl_team="Gujarat Titans", role = "allrounder", credits=7.5),
            Player(name="Kumar Kushagra", ipl_team="Gujarat Titans", role = "keeper", credits=7.5),
            Player(name="Jayant Yadav", ipl_team="Gujarat Titans", role = "bowler", credits=7),
            Player(name="Ashok Sharma", ipl_team="Gujarat Titans", role = "bowler", credits=7),
            Player(name="Gurnoor Brar", ipl_team="Gujarat Titans", role = "bowler", credits=7),
            Player(name="Prithvi Raj", ipl_team="Gujarat Titans", role = "bowler", credits=7),
            Player(name="Kulwant Khejroliya", ipl_team="Gujarat Titans", role = "allrounder", credits=8),
            Player(name="Sunil Narine", ipl_team="Kolkata Knight Riders", role = "allrounder", credits=9),
            Player(name="Varun Chakravarthy", ipl_team="Kolkata Knight Riders", role = "bowler", credits=9.5),
            Player(name="Cameron Green", ipl_team="Kolkata Knight Riders", role = "allrounder", credits=10),
            Player(name="Tim Seifert", ipl_team="Kolkata Knight Riders", role = "keeper", credits=8.5),
            Player(name="Finn Allen", ipl_team="Kolkata Knight Riders", role = "batsman", credits=9),
            Player(name="Rinku Singh", ipl_team="Kolkata Knight Riders", role = "batsman", credits=9),
            Player(name="Vaibhav Arora", ipl_team="Kolkata Knight Riders", role = "bowler", credits=8.5),
            Player(name="Matheesha Pathirana", ipl_team="Kolkata Knight Riders", role = "bowler", credits=8.5),
            Player(name="Ajinkya Rahane", ipl_team="Kolkata Knight Riders", role = "batsman", credits=9),
            Player(name="Angkrish Raghuvanshi", ipl_team="Kolkata Knight Riders", role = "batsman", credits=8.5),
            Player(name="Rachin Ravindra", ipl_team="Kolkata Knight Riders", role = "allrounder", credits=8.5),
            Player(name="Rahul Tripathi", ipl_team="Kolkata Knight Riders", role = "batsman", credits=8.5),
            Player(name="Rovman Powell", ipl_team="Kolkata Knight Riders", role = "batsman", credits=8),
            Player(name="Ramandeep Singh", ipl_team="Kolkata Knight Riders", role = "allrounder", credits=8.5),
            Player(name="Anukul Roy", ipl_team="Kolkata Knight Riders", role = "allrounder", credits=8.5),
            Player(name="Manish Pandey", ipl_team="Kolkata Knight Riders", role = "batsman", credits=8.5),
            Player(name="Umran Malik", ipl_team="Kolkata Knight Riders", role = "bowler", credits=8),
            Player(name="Kartik Tyagi", ipl_team="Kolkata Knight Riders", role = "bowler", credits=8),
            Player(name="Prashant Solanki", ipl_team="Kolkata Knight Riders", role = "bowler", credits=7.5),
            Player(name="Daksh Kamra", ipl_team="Kolkata Knight Riders", role = "allrounder", credits=7),
            Player(name="Sarthak Ranjan", ipl_team="Kolkata Knight Riders", role = "batsman", credits=7),
            Player(name="Tejasvi Dahiya", ipl_team="Kolkata Knight Riders", role = "keeper", credits=7),
            Player(name="Blessing Muzarabani", ipl_team="Kolkata Knight Riders", role = "bowler", credits=8.5),
            Player(name="Saurabh Dubey", ipl_team="Kolkata Knight Riders", role = "bowler", credits=7.5),
            Player(name="Navdeep Saini", ipl_team="Kolkata Knight Riders", role = "bowler", credits=8),
            Player(name="Mitchell Marsh", ipl_team="Lucknow Super Giants", role = "allrounder", credits=9.5),
            Player(name="Aiden Markram", ipl_team="Lucknow Super Giants", role = "allrounder", credits=10),
            Player(name="Nicholas Pooran", ipl_team="Lucknow Super Giants", role = "keeper", credits=9),
            Player(name="Rishabh Pant", ipl_team="Lucknow Super Giants", role = "keeper", credits=9.5),
            Player(name="Josh Inglis", ipl_team="Lucknow Super Giants", role = "keeper", credits=8.5),
            Player(name="Wanindu Hasaranga", ipl_team="Lucknow Super Giants", role = "allrounder", credits=8.5),
            Player(name="Mohammed Shami", ipl_team="Lucknow Super Giants", role = "bowler", credits=8.5),
            Player(name="Ayush Badoni", ipl_team="Lucknow Super Giants", role = "allrounder", credits=8),
            Player(name="Digvesh Rathi", ipl_team="Lucknow Super Giants", role = "bowler", credits=8.5),
            Player(name="Avesh Khan", ipl_team="Lucknow Super Giants", role = "bowler", credits=8.5),
            Player(name="Abdul Samad", ipl_team="Lucknow Super Giants", role = "batsman", credits=8),
            Player(name="Shahbaz Ahmed", ipl_team="Lucknow Super Giants", role = "allrounder", credits=8.5),
            Player(name="Mohsin Khan", ipl_team="Lucknow Super Giants", role = "bowler", credits=8),
            Player(name="Mayank Yadav", ipl_team="Lucknow Super Giants", role = "bowler", credits=8.5),
            Player(name="Prince Yadav", ipl_team="Lucknow Super Giants", role = "bowler", credits=8),
            Player(name="Arshin Kulkarni", ipl_team="Lucknow Super Giants", role = "allrounder", credits=8),
            Player(name="Anrich Nortje", ipl_team="Lucknow Super Giants", role = "bowler", credits=8.5),
            Player(name="Akash Singh", ipl_team="Lucknow Super Giants", role = "bowler", credits=7.5),
            Player(name="Manimaran Siddharth", ipl_team="Lucknow Super Giants", role = "bowler", credits=7.5),
            Player(name="Himmat Singh", ipl_team="Lucknow Super Giants", role = "batsman", credits=7),
            Player(name="Matthew Breetzke", ipl_team="Lucknow Super Giants", role = "batsman", credits=7.5),
            Player(name="Arjun Tendulkar", ipl_team="Lucknow Super Giants", role = "bowler", credits=7.5),
            Player(name="Akshat Raghuwanshi", ipl_team="Lucknow Super Giants", role = "batsman", credits=7),
            Player(name="Mukul Choudhary", ipl_team="Lucknow Super Giants", role = "batsman", credits=7),
            Player(name="Naman Tiwari", ipl_team="Lucknow Super Giants", role = "bowler", credits=7),
            Player(name="Suryakumar Yadav", ipl_team="Mumbai Indians", role = "batsman", credits=10.5),
            Player(name="Jasprit Bumrah", ipl_team="Mumbai Indians", role = "bowler", credits=9.5),
            Player(name="Trent Boult", ipl_team="Mumbai Indians", role = "bowler", credits=8.5),
            Player(name="Rohit Sharma", ipl_team="Mumbai Indians", role = "batsman", credits=9.5),
            Player(name="Hardik Pandya", ipl_team="Mumbai Indians", role = "allrounder", credits=10),
            Player(name="Tilak Varma", ipl_team="Mumbai Indians", role = "batsman", credits=9),
            Player(name="Ryan Rickelton", ipl_team="Mumbai Indians", role = "keeper", credits=8.5),
            Player(name="Mitchell Santner", ipl_team="Mumbai Indians", role = "allrounder", credits=8.5),
            Player(name="Quinton de Kock", ipl_team="Mumbai Indians", role = "keeper", credits=8.5),
            Player(name="Will Jacks", ipl_team="Mumbai Indians", role = "allrounder", credits=8.5),
            Player(name="Deepak Chahar", ipl_team="Mumbai Indians", role = "bowler", credits=8.5),
            Player(name="Shardul Thakur", ipl_team="Mumbai Indians", role = "bowler", credits=8.5),
            Player(name="Sherfane Rutherford", ipl_team="Mumbai Indians", role = "batsman", credits=8.5),
            Player(name="Naman Dhir", ipl_team="Mumbai Indians", role = "allrounder", credits=8.5),
            Player(name="Ashwani Kumar", ipl_team="Mumbai Indians", role = "bowler", credits=8),
            Player(name="Corbin Bosch", ipl_team="Mumbai Indians", role = "allrounder", credits=8.5),
            Player(name="AM Ghazanfar", ipl_team="Mumbai Indians", role = "bowler", credits=8),
            Player(name="Mayank Markande", ipl_team="Mumbai Indians", role = "bowler", credits=8),
            Player(name="Raj Bawa", ipl_team="Mumbai Indians", role = "allrounder", credits=7.5),
            Player(name="Robin Minz", ipl_team="Mumbai Indians", role = "keeper", credits=7.5),
            Player(name="Raghu Sharma", ipl_team="Mumbai Indians", role = "bowler", credits=7),
            Player(name="Atharva Ankolekar", ipl_team="Mumbai Indians", role = "allrounder", credits=7),
            Player(name="Danish Malewar", ipl_team="Mumbai Indians", role = "batsman", credits=7),
            Player(name="Mayank Rawat", ipl_team="Mumbai Indians", role = "allrounder", credits=7),
            Player(name="Mohd Izhar", ipl_team="Mumbai Indians", role = "bowler", credits=7),
            Player(name="Shreyas Iyer", ipl_team="Punjab Kings", role = "batsman", credits=11),
            Player(name="Arshdeep Singh", ipl_team="Punjab Kings", role = "bowler", credits=9),
            Player(name="Marco Jansen", ipl_team="Punjab Kings", role = "allrounder", credits=9),
            Player(name="Azmatullah Omarzai", ipl_team="Punjab Kings", role = "allrounder", credits=8.5),
            Player(name="Marcus Stoinis", ipl_team="Punjab Kings", role = "allrounder", credits=9),
            Player(name="Prabhsimran Singh", ipl_team="Punjab Kings", role = "keeper", credits=9),
            Player(name="Priyansh Arya", ipl_team="Punjab Kings", role = "batsman", credits=8.5),
            Player(name="Yuzvendra Chahal", ipl_team="Punjab Kings", role = "bowler", credits=8.5),
            Player(name="Nehal Wadhera", ipl_team="Punjab Kings", role = "batsman", credits=8.5),
            Player(name="Harpreet Brar", ipl_team="Punjab Kings", role = "bowler", credits=8),
            Player(name="Shashank Singh", ipl_team="Punjab Kings", role = "allrounder", credits=8),
            Player(name="Lockie Ferguson", ipl_team="Punjab Kings", role = "bowler", credits=8.5),
            Player(name="Mitchell Owen", ipl_team="Punjab Kings", role = "batsman", credits=8),
            Player(name="Ben Dwarshuis", ipl_team="Punjab Kings", role = "bowler", credits=8),
            Player(name="Cooper Connolly", ipl_team="Punjab Kings", role = "allrounder", credits=8.5),
            Player(name="Vijaykumar Vyshak", ipl_team="Punjab Kings", role = "bowler", credits=8.5),
            Player(name="Xavier Bartlett", ipl_team="Punjab Kings", role = "bowler", credits=8.5),
            Player(name="Suryansh Shedge", ipl_team="Punjab Kings", role = "allrounder", credits=8),
            Player(name="Praveen Dubey", ipl_team="Punjab Kings", role = "bowler", credits=7.5),
            Player(name="Yash Thakur", ipl_team="Punjab Kings", role = "bowler", credits=7.5),
            Player(name="Musheer Khan", ipl_team="Punjab Kings", role = "allrounder", credits=7),
            Player(name="Vishnu Vinod", ipl_team="Punjab Kings", role = "keeper", credits=7.5),
            Player(name="Harnoor Singh", ipl_team="Punjab Kings", role = "batsman", credits=7.5),
            Player(name="Pyla Avinash", ipl_team="Punjab Kings", role = "batsman", credits=7),
            Player(name="Vishal Nishad", ipl_team="Punjab Kings", role = "bowler", credits=7),
            Player(name="Yashasvi Jaiswal", ipl_team="Rajasthan Royals", role = "batsman", credits=10.5),
            Player(name="Ravindra Jadeja", ipl_team="Rajasthan Royals", role = "allrounder", credits=9.5),
            Player(name="Shimron Hetmyer", ipl_team="Rajasthan Royals", role = "batsman", credits=9),
            Player(name="Riyan Parag", ipl_team="Rajasthan Royals", role = "allrounder", credits=8.5),
            Player(name="Jofra Archer", ipl_team="Rajasthan Royals", role = "bowler", credits=8.5),
            Player(name="Dhruv Jurel", ipl_team="Rajasthan Royals", role = "keeper", credits=8.5),
            Player(name="Vaibhav Sooryavanshi", ipl_team="Rajasthan Royals", role = "batsman", credits=8.5),
            Player(name="Ravi Bishnoi", ipl_team="Rajasthan Royals", role = "bowler", credits=8.5),
            Player(name="Tushar Deshpande", ipl_team="Rajasthan Royals", role = "bowler", credits=8.5),
            Player(name="Sandeep Sharma", ipl_team="Rajasthan Royals", role = "bowler", credits=8.5),
            Player(name="Nandre Burger", ipl_team="Rajasthan Royals", role = "bowler", credits=8.5),
            Player(name="Adam Milne", ipl_team="Rajasthan Royals", role = "bowler", credits=8.5),
            Player(name="Donovan Ferreira", ipl_team="Rajasthan Royals", role = "allrounder", credits=8),
            Player(name="Lhuan-dre Pretorius", ipl_team="Rajasthan Royals", role = "keeper", credits=8.5),
            Player(name="Yudhvir Singh", ipl_team="Rajasthan Royals", role = "bowler", credits=8),
            Player(name="Kuldeep Sen", ipl_team="Rajasthan Royals", role = "bowler", credits=8),
            Player(name="Kwena Maphaka", ipl_team="Rajasthan Royals", role = "bowler", credits=8),
            Player(name="Vignesh Puthur", ipl_team="Rajasthan Royals", role = "allrounder", credits=7.5),
            Player(name="Shubham Dubey", ipl_team="Rajasthan Royals", role = "batsman", credits=7.5),
            Player(name="Sushant Mishra", ipl_team="Rajasthan Royals", role = "bowler", credits=7),
            Player(name="Aman Rao", ipl_team="Rajasthan Royals", role = "batsman", credits=7),
            Player(name="Brijesh Sharma", ipl_team="Rajasthan Royals", role = "bowler", credits=7),
            Player(name="Ravi Singh", ipl_team="Rajasthan Royals", role = "batsman", credits=7),
            Player(name="Yash Raj Punja", ipl_team="Rajasthan Royals", role = "bowler", credits=7),
            Player(name="Dasun Shanaka", ipl_team="Rajasthan Royals", role = "allrounder", credits=8.5),
            Player(name="Josh Hazlewood", ipl_team="Royal Challengers Bengaluru", role = "bowler", credits=9),
            Player(name="Virat Kohli", ipl_team="Royal Challengers Bengaluru", role = "batsman", credits=11),
            Player(name="Krunal Pandya", ipl_team="Royal Challengers Bengaluru", role = "allrounder", credits=9),
            Player(name="Phil Salt", ipl_team="Royal Challengers Bengaluru", role = "keeper", credits=9.5),
            Player(name="Rajat Patidar", ipl_team="Royal Challengers Bengaluru", role = "batsman", credits=9.5),
            Player(name="Bhuvneshwar Kumar", ipl_team="Royal Challengers Bengaluru", role = "bowler", credits=8.5),
            Player(name="Tim David", ipl_team="Royal Challengers Bengaluru", role = "batsman", credits=8.5),
            Player(name="Venkatesh Iyer", ipl_team="Royal Challengers Bengaluru", role = "allrounder", credits=8.5),
            Player(name="Jitesh Sharma", ipl_team="Royal Challengers Bengaluru", role = "keeper", credits=8.5),
            Player(name="Suyash Sharma", ipl_team="Royal Challengers Bengaluru", role = "bowler", credits=8.5),
            Player(name="Romario Shepherd", ipl_team="Royal Challengers Bengaluru", role = "allrounder", credits=8.5),
            Player(name="Devdutt Padikkal", ipl_team="Royal Challengers Bengaluru", role = "batsman", credits=8.5),
            Player(name="Jacob Duffy", ipl_team="Royal Challengers Bengaluru", role = "bowler", credits=8.5),
            Player(name="Jordan Cox", ipl_team="Royal Challengers Bengaluru", role = "keeper", credits=8),
            Player(name="Jacob Bethell", ipl_team="Royal Challengers Bengaluru", role = "allrounder", credits=8),
            Player(name="Nuwan Thushara", ipl_team="Royal Challengers Bengaluru", role = "bowler", credits=8),
            Player(name="Vicky Ostwal", ipl_team="Royal Challengers Bengaluru", role = "bowler", credits=8),
            Player(name="Rasikh Salam", ipl_team="Royal Challengers Bengaluru", role = "bowler", credits=8),
            Player(name="Abhinandan Singh", ipl_team="Royal Challengers Bengaluru", role = "bowler", credits=7.5),
            Player(name="Swapnil Singh", ipl_team="Royal Challengers Bengaluru", role = "allrounder", credits=7),
            Player(name="Kanishk Chouhan", ipl_team="Royal Challengers Bengaluru", role = "allrounder", credits=7),
            Player(name="Mangesh Yadav", ipl_team="Royal Challengers Bengaluru", role = "allrounder", credits=7),
            Player(name="Satvik Deswal", ipl_team="Royal Challengers Bengaluru", role = "bowler", credits=7),
            Player(name="Vihaan Malhotra", ipl_team="Royal Challengers Bengaluru", role = "allrounder", credits=7),
            Player(name="Abhishek Sharma", ipl_team="Sunrisers Hyderabad", role = "allrounder", credits=10.5),
            Player(name="Travis Head", ipl_team="Sunrisers Hyderabad", role = "batsman", credits=10),
            Player(name="Heinrich Klaasen", ipl_team="Sunrisers Hyderabad", role = "keeper", credits=9),
            Player(name="Pat Cummins", ipl_team="Sunrisers Hyderabad", role = "allrounder", credits=8.5),
            Player(name="Ishan Kishan", ipl_team="Sunrisers Hyderabad", role = "keeper", credits=9.5),
            Player(name="Nitish Kumar Reddy", ipl_team="Sunrisers Hyderabad", role = "allrounder", credits=9),
            Player(name="Harshal Patel", ipl_team="Sunrisers Hyderabad", role = "allrounder", credits=8.5),
            Player(name="Jaydev Unadkat", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=8.5),
            Player(name="Liam Livingstone", ipl_team="Sunrisers Hyderabad", role = "allrounder", credits=8.5),
            Player(name="Kamindu Mendis", ipl_team="Sunrisers Hyderabad", role = "allrounder", credits=8),
            Player(name="Shivam Mavi", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=8.5),
            Player(name="Brydon Carse", ipl_team="Sunrisers Hyderabad", role = "allrounder", credits=8.5),
            Player(name="Zeeshan Ansari", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=8),
            Player(name="Eshan Malinga", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=7.5),
            Player(name="Aniket Verma", ipl_team="Sunrisers Hyderabad", role = "batsman", credits=7.5),
            Player(name="Harsh Dubey", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=7),
            Player(name="Ravichandran Smaran", ipl_team="Sunrisers Hyderabad", role = "batsman", credits=7),
            Player(name="Sakib Hussain", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=7),
            Player(name="Amit Kumar", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=7),
            Player(name="Krains Fuletra", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=7),
            Player(name="Onkar Tarmale", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=7),
            Player(name="Praful Hinge", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=7),
            Player(name="Salil Arora", ipl_team="Sunrisers Hyderabad", role = "keeper", credits=7),
            Player(name="Shivang Kumar", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=7),
            Player(name="David Payne", ipl_team="Sunrisers Hyderabad", role = "bowler", credits=7.5),
        ]
        db.session.add_all(players)
        db.session.commit()
        print(f"✅ {len(players)} players seeded successfully!")

def seed_matches():
    if True:  # context already active when called from app.py
        Match.query.delete()
        db.session.commit()

        matches = [
            Match(match_number=1, team1="Royal Challengers Bengaluru", team2="Sunrisers Hyderabad",
                  venue="M. Chinnaswamy Stadium, Bengaluru", match_date=datetime(2026, 3, 28, 19, 30),
                  status="completed", cricapi_match_id="55fe0f15-6eb0-4ad5-835b-5564be4f6a21"),
            Match(match_number=2, team1="Mumbai Indians", team2="Kolkata Knight Riders",
                  venue="Wankhede Stadium, Mumbai", match_date=datetime(2026, 3, 29, 19, 30),
                  status="completed", cricapi_match_id="e02475c1-8f9a-4915-a9e8-d4dbc3441c96"),
            Match(match_number=3, team1="Rajasthan Royals", team2="Chennai Super Kings",
                  venue="Sawai Mansingh Stadium, Jaipur", match_date=datetime(2026, 3, 30, 19, 30),
                  status="completed", cricapi_match_id="d788e9f9-99bf-4650-a035-92a7e21b3d08"),
            Match(match_number=4, team1="Punjab Kings", team2="Gujarat Titans",
                  venue="Punjab Cricket Association Stadium, Mohali", match_date=datetime(2026, 3, 31, 19, 30),
                  status="completed", cricapi_match_id="11ff7db9-9c71-464e-afcb-5b03e4fa4b0a"),
            Match(match_number=5, team1="Lucknow Super Giants", team2="Delhi Capitals",
                  venue="BRSABV Ekana Cricket Stadium, Lucknow", match_date=datetime(2026, 4, 1, 19, 30),
                  status="completed", cricapi_match_id="ae676d7c-3082-489c-96c5-5620f393c900"),
            Match(match_number=6, team1="Kolkata Knight Riders", team2="Sunrisers Hyderabad",
                  venue="Eden Gardens, Kolkata", match_date=datetime(2026, 4, 2, 19, 30),
                  status="completed", cricapi_match_id="fd010e39-2255-4460-b0e0-962a26b67b70"),
            Match(match_number=7, team1="Chennai Super Kings", team2="Punjab Kings",
                  venue="MA Chidambaram Stadium, Chennai", match_date=datetime(2026, 4, 3, 19, 30),
                  status="completed", cricapi_match_id="96d2aa6b-ea40-4da4-b4cf-eb996de24ef7"),
            Match(match_number=8, team1="Gujarat Titans", team2="Rajasthan Royals",
                  venue="Narendra Modi Stadium, Ahmedabad", match_date=datetime(2026, 4, 4, 19, 30),
                  status="completed", cricapi_match_id="ea4d01bf-bf47-4f7d-a4f8-32eade678141"),
            Match(match_number=9, team1="Sunrisers Hyderabad", team2="Lucknow Super Giants",
                  venue="Rajiv Gandhi Stadium, Hyderabad", match_date=datetime(2026, 4, 5, 19, 30),
                  status="completed", cricapi_match_id="e43dd29e-c60e-40c9-a6c4-6c1bd69dd671"),
            Match(match_number=10, team1="Royal Challengers Bengaluru", team2="Chennai Super Kings",
                  venue="M. Chinnaswamy Stadium, Bengaluru", match_date=datetime(2026, 4, 5, 15, 30),
                  status="completed", cricapi_match_id="e92727d0-61fc-4c6f-82ed-cde4789745a2"),
            Match(match_number=11, team1="Kolkata Knight Riders", team2="Punjab Kings",
                  venue="Eden Gardens, Kolkata", match_date=datetime(2026, 4, 6, 19, 30),
                  status="completed", cricapi_match_id="adeebb28-bc39-439b-99ed-2daef5106232"),
            Match(match_number=12, team1="Rajasthan Royals", team2="Mumbai Indians",
                  venue="Sawai Mansingh Stadium, Jaipur", match_date=datetime(2026, 4, 7, 19, 30),
                  status="upcoming", cricapi_match_id="4f617f5e-c635-4989-b135-5430dc73c5d7"),
            Match(match_number=13, team1="Delhi Capitals", team2="Gujarat Titans",
                  venue="Arun Jaitley Stadium, Delhi", match_date=datetime(2026, 4, 8, 19, 30),
                  status="upcoming", cricapi_match_id="12496498-8526-46d9-a053-da2ba8d047e1"),
            Match(match_number=14, team1="Kolkata Knight Riders", team2="Lucknow Super Giants",
                  venue="Eden Gardens, Kolkata", match_date=datetime(2026, 4, 9, 19, 30),
                  status="upcoming", cricapi_match_id="c78dcc8a-67cf-460a-8f2b-8f16d3891682"),
            Match(match_number=15, team1="Rajasthan Royals", team2="Royal Challengers Bengaluru",
                  venue="Sawai Mansingh Stadium, Jaipur", match_date=datetime(2026, 4, 10, 19, 30),
                  status="upcoming", cricapi_match_id="05a88a74-0e68-47d9-996b-257b3b1ebf8d"),
            Match(match_number=16, team1="Punjab Kings", team2="Sunrisers Hyderabad",
                  venue="Punjab Cricket Association Stadium, Mohali", match_date=datetime(2026, 4, 11, 19, 30),
                  status="upcoming", cricapi_match_id="a4cd9851-d79a-42b6-8a4b-b35cbb9f9f0a"),
            Match(match_number=17, team1="Chennai Super Kings", team2="Delhi Capitals",
                  venue="MA Chidambaram Stadium, Chennai", match_date=datetime(2026, 4, 11, 15, 30),
                  status="upcoming", cricapi_match_id="204afd0a-026a-41f4-afda-653030a84e46"),
            Match(match_number=18, team1="Mumbai Indians", team2="Royal Challengers Bengaluru",
                  venue="Wankhede Stadium, Mumbai", match_date=datetime(2026, 4, 12, 19, 30),
                  status="upcoming", cricapi_match_id="11d553de-3b2a-4e58-9abd-4bb7d575595e"),
            Match(match_number=19, team1="Lucknow Super Giants", team2="Gujarat Titans",
                  venue="BRSABV Ekana Cricket Stadium, Lucknow", match_date=datetime(2026, 4, 12, 15, 30),
                  status="upcoming", cricapi_match_id="36d875e2-3333-4fab-ba4d-4f89fb4d7055"),
        ]

        db.session.add_all(matches)
        db.session.commit()
        print(f"✅ {len(matches)} matches seeded successfully!")

if __name__ == "__main__":
    from app import app
    with app.app_context():
      seed_players()
      seed_matches()